name: wf-context
on: [push]

jobs:
    wf-context-step:
        runs-on: ubuntu-latest
        steps:
            - name: github context
              run: |
                echo "Hello ${{github.action_status}}"
                echo "Hello ${{github.actor}}"
              env:
                myaction: ${{github.action}}
                myactor: ${{github.actor}}
